services:
  db:
    image: postgres:17-alpine
    container_name: db_biblioteca
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    ports:
      - "5433:5432"
    shm_size: 128mb
    restart: always
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: